pipeline {
    agent any
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Branch to build')
        booleanParam(name: 'SKIP_TESTS', defaultValue: true, description: 'Skip tests during build')
    }
    stages {
        stage('Demo') {
            steps {
                echo "boolean param Bbranch nameis set to: ${params.SKIP_TESTS}"
                echo "string param skip tests is set to: ${params.BRANCH_NAME}"
            }
        }
    }
}
